---
# AWS Step Functions state machines example.
files:
  - path: stepfunctions_basics.py
    services:
      - stepfunctions
  - path: test/conftest.py
    services:
      - stepfunctions
  - path: test/test_stepfunctions_basics.py
    services:
      - stepfunctions
...